### ISSUE TITLE
In Bugzilla, show coverage information in the uplift request comments

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage-addon#10]
cc @sylvestre

**Comment by marco-c** [comment]
Here's an example bug where there is an uplift request: https://bugzilla.mozilla.org/show_bug.cgi?id=1444158.
The uplift request is in comment 1: https://bugzilla.mozilla.org/show_bug.cgi?id=1444158#c1.

At the moment, the coverage information is only put in a "Code Coverage" field in the "Details" section.
It should be put in a new line of the uplift request comment too, between `[Is this code covered by automated tests?]` and `[Has the fix been verified in Nightly?]`.

The Bugzilla-related code of the extension is at https://github.com/marco-c/code-coverage-addon/blob/master/bugzilla.js.

**Comment by varshika03** [comment]
Can I work on this issue?

**Comment by marco-c** [comment]
Sure, any issue that is still open and doesn't have a linked PR is available for anyone to pick up. Issues are assigned when someone submits a PR to fix them.

**Comment by divyabaid16** [comment]
@marco-c I added the extension in my browser but I couldn't find the "Code coverage" field in the "Details" section of the link you provided.

**Comment by marco-c** [comment]
Sorry, that's a bad example as the patch hasn't been merged yet. You can see the field in the "Details" section if you load https://bugzilla.mozilla.org/show_bug.cgi?id=1405567.

**Comment by divyabaid16** [comment]
@marco-c  how can I find ```[Is this code covered by automated tests?]``` 
From so many comments how will I find the Uplift request comment?
What container should be used?

**Comment by marco-c** [comment]
You'll need to loop through the comments and find all the comments that have an uplift request.
