### ISSUE TITLE
Don't overwrite eslint mozilla/recommended rules

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage-addon#23]
Except the 'indent' rule, we don't want to overwrite anything from the mozilla/recommended rules.

**Comment by rhcu** [comment]
Hi, 
I think that we can just delete lines from 39 till 51 in  .eslintrc.js file so that this rules will be the default recommended rules. Am I right? If yes, can I do this? 
Thanks.

**Comment by marco-c** [comment]
Yes! Sure ;)
When you remove the rules, you also need to make sure the linting is still successful and fix any issue that might come up.
