### ISSUE TITLE
line_no is undefined on Searchfox

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage-addon#29]

**Comment by Juniar-II** [comment]
Can you explain this part or give a description of undefined search box with the source files.

**Comment by rhcu** [comment]
Hi @Juniar-II,
I am not sure if I am right but would be happy to help. :)

You can try to search in this repository for the keyword `line_no` to see that there are parts of code in `dxr.js` 
 [~line 31] and in `mozreview.js` [~line 86] that define `line_no` value, while there is nothing relevant to `line_no` in `searchfox.js`; therefore it is undefined as it is said in the issue.

**Comment by Juniar-II** [comment]
Thanks for the explanation. How you run the repo code-coverage-addon? do you need an application to generate html files. I would like to view editing on .html files.

**Comment by marco-c** [comment]
The explanation isn't correct.

line_no is defined here: https://github.com/marco-c/code-coverage-addon/blob/master/dxr-common.js#L31.
dxr-common.js is used both in Searchfox and in DXR.
For some reason, while this works in DXR (the element can be found), it doesn't work in Searchfox (the element can't be found). It used to work on Searchfox, so there must be something that changed.

@Juniar-II this is an addon, if you want to run it you can either use [web-ext](https://github.com/mozilla/web-ext), or open "about:debugging", select "Load a temporary addon" and select the manifest.json file from the repo. Don't forget to run "npm run build" first.

**Comment by rhcu** [comment]
I am very sorry for the wrong explanation. 
I could not find lines relevant to `line_no` in Searchfox JS file and thought that this issue is about defining it there.

**Comment by marco-c** [comment]
> I am very sorry for the wrong explanation.
I could not find lines relevant to line_no in Searchfox JS file and thought that this issue is about defining it there.

No worries ;)

**Comment by Juniar-II** [comment]
The line_no does not exist on the Searchfox.js and I think it should be defined there. Unless we can call it from dxr-common.js where it has been defined. I look up on Searchfox.js and is undefined.

**Comment by marco-c** [comment]
> The line_no does not exist on the Searchfox.js and I think it should be defined there. Unless we can call it from dxr-common.js where it has been defined. I look up on Searchfox.js and is undefined.

No, it shouldn't be defined in Searchfox.js.

**Comment by Juniar-II** [comment]
There is no reference or any function on Searchfox.js that calls line_no.

**Comment by marco-c** [comment]
`applyOverlay`, where line_no is used, is called by `injectToggle`, which is called in searchfox.js: https://github.com/marco-c/code-coverage-addon/blob/f46984b7eb6c02a0f99979a550507b26e1cb368f/searchfox.js#L25.

**Comment by Juniar-II** [comment]
There are a couple of reasons that might be causing the error message.
1. line_no is defined as a const line_no on applyOverlay(revPromise, path).
2. line_no is defined inside another function  applyOverlay(revPromise, path) and can only be accessed within its scope.

So you might be trying to make a reference to a class variable.

**Comment by marco-c** [comment]
@Juniar-II, I think you are misunderstanding this. Do you know what `undefined` means in JavaScript?

> line_no is defined as a const line_no on applyOverlay(revPromise, path).

The fact that `line_no` is a constant has nothing to do with the fact that it was undefined.

> line_no is defined inside another function applyOverlay(revPromise, path) and can only be accessed within its scope.

No, `applyOverlay` is the only place where `line_no` is defined.

> So you might be trying to make a reference to a class variable.

This makes no sense in the context of this issue...
