### ISSUE TITLE
Don't stop detecting comments when an element with ID cXXX doesn't exist

### ISSUE THREAD

**Issue by sylvestre** [mozilla/code-coverage-addon#31]
For example, on https://bugzilla.mozilla.org/show_bug.cgi?id=1449212
We don't have the coverage information:
https://screenshots.firefox.com/QUK6i8VwfghU26Sy/bugzilla.mozilla.org

We should clearly state that we don't have the information yet.

**Comment by marco-c** [comment]
The bug here is that the addon doesn't detect all the comments, so it doesn't see the comment with the uplift request.
It loops from c0 to cXXX until cXXX doesn't exist, but on this page c8 exists, c9 doesn't exist, c10 exists, so the addon stops at c8.
