### ISSUE TITLE
Remove support for MozReview

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage-addon#47]

**Comment by arshadkazmi42** [comment]
@MandyRawls i would like to work on, for this just need to remove the mozreview file? or there is something else to it?

**Comment by marco-c** [comment]
Hello @arshadkazmi42! You'll need to remove the mozreview.js file and any reference to it, plus the permission from the manifest that requests access to mozreview, plus any "MozReview" reference from the documentation.

**Comment by arshadkazmi42** [comment]
@marco-c Thanks for clearing my doubt. I will be working on this now.
