### ISSUE TITLE
Remove Bugzilla support

### ISSUE THREAD

**Issue by marco-c** [mozilla/code-coverage-addon#54]
Given that we upload coverage directly to Phabricator, Bugzilla support doesn't seem necessary anymore.

**Comment by melvin2016** [comment]
where should i start removing the references?

**Comment by marco-c** [comment]
The bugzilla.js file and every function that is used by that file and not by any other file, then you can also remove https://github.com/mozilla/code-coverage-addon/blob/master/manifest.json#L24.

**Comment by melvin2016** [comment]
Made PR #55 as a fix.
